# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WalletApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PhoneNumberKit'
  pod "Gradients"
  # Pods for WalletApp

  target 'WalletAppTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'WalletAppUITests' do
    # Pods for testing
  end

end
